name: base

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    env:
      CQTDEPLOYER_VERSION: 1.4.7
      CQTDEPLOYER_INSTALLATION_DIR: ${{ github.workspace }}/CQtDeployer_installation
      QT_INSTALLER_NONINTERACTIVE_SCRIPT_PATH: ${{ github.workspace }}/.github/workflows/qt-installer-noninteractive.qs
      DOWNLOADED_FILE_DIR: ${{ github.workspace }}
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      matrix:
        qt_ver: [5.15.0, 5.15.1, 5.15.2]
        branch_name: [v1.5, task_481]

    steps:
      - name: Don't direct call 'mingw32-make.exe'
        run: Get-Command -Name 'mingw32-make.exe' | Format-List

      # To get '.github/workflows/qt-installer-noninteractive.qs'
      - name: checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          host: windows
          target: desktop
          arch: win64_mingw81
          tools: "tools_ifw,4.0.1-202012091044,qt.tools.ifw.40 tools_mingw,8.1.0-1-202004170606,qt.tools.win64_mingw810"
          aqtversion: "==0.10.1"
          py7zrversion: "==0.11.1"

      - name: Inspect Qt
        run: |
          Get-Command -Name 'qmake.exe' | Format-List
          $p = Start-Process -Wait -NoNewWindow -PassThru -FilePath "qmake.exe" -ArgumentList @('-query');
          If ($p.ExitCode -ne 0) { Exit $p.ExitCode }

          Get-ItemProperty -Path "${Env:\Qt5_Dir}\..\..\Tools\mingw810_64\bin\mingw32-make.exe"

      - name: clone QuasarApp/CQtDeployer@${{ matrix.branch_name }}
        run: |
          $p = Start-Process -Wait -NoNewWindow -PassThru -FilePath "git" -ArgumentList @(
            'clone',
            '--recurse-submodules',
            '--branch', '${{ matrix.branch_name }}'
            '--single-branch',
            'https://github.com/QuasarApp/CQtDeployer.git'
          )
          If ($p.ExitCode -ne 0) { Exit $p.ExitCode }

          Push-Location -Path CQtDeployer\

          $p = Start-Process -Wait -NoNewWindow -PassThru -FilePath "git" -ArgumentList @(
            'log', '-n1'
          )
          If ($p.ExitCode -ne 0) { Exit $p.ExitCode }

          Pop-Location

      - name: Download CQtDeployer
        uses: suisei-cn/actions-download-file@v1
        id: downloadCqt
        with:
          url: "https://github.com/QuasarApp/CQtDeployer/releases/download/${{ env.CQTDEPLOYER_VERSION }}/WindowsOfflineInstaller.exe"
          target: ${{ github.workspace }}

      - name: Install CQtDeployer
        run: |
          $installer_path = "${Env:\DOWNLOADED_FILE_DIR}\${{ steps.downloadCqt.outputs.filename }}"
          Get-ItemProperty -Path "$installer_path"

          $p = Start-Process -Wait -NoNewWindow -PassThru -FilePath "$installer_path" -ArgumentList @(
            '--script', "${Env:\QT_INSTALLER_NONINTERACTIVE_SCRIPT_PATH}",
            '--verbose',
            "targetDirectory=`"${Env:\CQTDEPLOYER_INSTALLATION_DIR}`""
          )
          If ($p.ExitCode -ne 0) { Exit $p.ExitCode }
          Get-ItemProperty -Path "${Env:\CQTDEPLOYER_INSTALLATION_DIR}\1.4\bin\cqtdeployer.exe"

          Push-Location -Path "${Env:\CQTDEPLOYER_INSTALLATION_DIR}\1.4\lib"

          $p = Start-Process -Wait -NoNewWindow -PassThru -FilePath '..\bin\cqtdeployer.exe'
          If ($p.ExitCode -ne 0) { Exit $p.ExitCode }

          Pop-Location

      - name: qmake CQtDeployer
        env:
          cqtdeployer: ${{ env.CQTDEPLOYER_INSTALLATION_DIR }}/1.4/cqtdeployer.bat # Will be saved in Makefile by qmake
        run: |
          Push-Location -Path CQtDeployer\

          $p = Start-Process -Wait -NoNewWindow -PassThru -FilePath "${Env:\Qt5_Dir}\bin\qmake.exe" -ArgumentList @('-recursive')
          If ($p.ExitCode -ne 0) { Exit $p.ExitCode }

          Pop-Location

      - name: make CQtDeployer
        run: |
          Push-Location -Path CQtDeployer\

          $p = Start-Process -Wait -NoNewWindow -PassThru -FilePath "${Env:\Qt5_Dir}\..\..\Tools\mingw810_64\bin\mingw32-make.exe" -ArgumentList @('-j2')
          If ($p.ExitCode -ne 0) { Exit $p.ExitCode }

          Pop-Location

      - name: test CQtDeployer
        id: tst_CQtDeployer
        run: |
          Push-Location -Path CQtDeployer\

          $p = Start-Process -Wait -NoNewWindow -PassThru -FilePath "${Env:\Qt5_Dir}\..\..\Tools\mingw810_64\bin\mingw32-make.exe" -ArgumentList @('test')
          # We need buildLog.log, so don't stop here.
          Write-Host "::set-output name=testExitCode::$($p.ExitCode.toString())"

          Write-Host '=== ${{ github.workspace }}/CQtDeployer/buildLog.log ==='
          Get-Content -LiteralPath "${{ github.workspace }}/CQtDeployer/buildLog.log"

          Pop-Location

      - name: Upload buildLog.log
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-CQtDeployer-${{ matrix.qt_ver }}-${{ matrix.qt_arch }}-${{ matrix.branch_name }}-buildLog.log
          path: ${{ github.workspace }}/CQtDeployer/buildLog.log

      - run: |
          $exitCode = ${{ steps.tst_CQtDeployer.outputs.testExitCode }}
          If ($exitCode -ne 0) { Exit $exitCode }
